name: wav2lip
services:
    wav2lip:
        image: brandonkovacs/wav2lip:latest
        container_name: wav2lip
        build:
          context: .
          dockerfile: Dockerfile
          shm_size: 8gb
        ports:
          - 8000:80
        shm_size: 8gb
        volumes:
          - ./workspace:/workspace
        entrypoint: bash -c "fastapi run /app/api.py --port 80"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
